app = "apis.rocks"
primary_region = "sin"

[build]
  dockerfile = "app/Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services.port]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.port]]
  port = 443
  handlers = ["tls", "http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 